<a href="https://colab.research.google.com/github/lilrachel1985/Diabetes/blob/main/diabetescopy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd

train_data_dir = ('https://drive.google.com/file/d/1S1u27Zy7r5rK68Bmf-7W-5GLRw4z5eHq/view?usp=drive_link')
print(train_data_dir)


https://drive.google.com/file/d/1S1u27Zy7r5rK68Bmf-7W-5GLRw4z5eHq/view?usp=drive_link


In [3]:
my_file = tf.keras.utils.get_file("diabetes.csv", 'https://drive.google.com/file/d/1S1u27Zy7r5rK68Bmf-7W-5GLRw4z5eHq/view?usp=drive_link')

   8192/Unknown - 0s 0us/step

1. Simple Batching

In [4]:
dataset_diab1 = tf.data.Dataset.range(100)
dataset_diab2 = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((dataset_diab1, dataset_diab2))


In [5]:


dataset = tf.data.Dataset.zip((dataset_diab1, dataset_diab2))

In [6]:

batched_dataset = dataset.batch(4)

for batch in batched_dataset.take(4):
  print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3]), array([ 0, -1, -2, -3])]
[array([4, 5, 6, 7]), array([-4, -5, -6, -7])]
[array([ 8,  9, 10, 11]), array([ -8,  -9, -10, -11])]
[array([12, 13, 14, 15]), array([-12, -13, -14, -15])]


In [7]:
batched_dataset

<_BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.int64, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [8]:

print("dataset after applying batch method")
for batch in batched_dataset:
    print(batch)

dataset after applying batch method
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 0, -1, -2, -3])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 5, 6, 7])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-4, -5, -6, -7])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 8,  9, 10, 11])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([ -8,  -9, -10, -11])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([12, 13, 14, 15])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-12, -13, -14, -15])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([16, 17, 18, 19])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-16, -17, -18, -19])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([20, 21, 22, 23])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-20, -21, -22, -23])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([24, 25, 26, 27])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-2

2. Batching tensors with padding

In [9]:
record_defaults = [999, 999] # Only provide defaults for the selected columns
dataset = tf.data.experimental.CsvDataset("diabetes.csv", record_defaults, select_cols=[1, 3])
dataset = dataset.map(lambda *items: tf.stack(items))
dataset

<_MapDataset element_spec=TensorSpec(shape=(2,), dtype=tf.int32, name=None)>

In [30]:
!pip install tensorflow_datasets

In [27]:
def get_dataset_partitions_tf(dataset, dataset_size, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1

    if shuffle:
        # Specify seed to always have the same split distribution between runs
        dataset = dataset.shuffle(shuffle_size, seed=12)

    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)

    train_ds = dataset.take(train_size)
    val_ds = dataset.skip(train_size).take(val_size)
    test_ds = dataset.skip(train_size).skip(val_size)

    return train_ds, val_ds, test_ds

In [10]:
!pip install scikit-plot

In [13]:
# Read in the training and evaluation datasets
from sklearn.model_selection import train_test_split
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/Diabetes.csv', skipinitialspace=True)

# Split the dataset. Do not shuffle for this demo notebook.
train_df, eval_df = train_test_split(df, test_size=0.2, shuffle=False)

In [14]:
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

In [54]:
DATASET_SIZE = tf.data.experimental.cardinality(dataset).numpy()
# Define the size of the training set
train_size = int(0.7 * DATASET_SIZE)
# Define the size of the validation set
val_size = int(0.15 * DATASET_SIZE)
# Define the size of the testing set
test_size = int(0.15 * DATASET_SIZE)

# Split the dataset into training and testing sets
# skip() that allows you to skip a certain number of elements in a dataset
# take() that allows you to take a certain number of elements from a dataset
train_dataset = dataset.take(train_size)
test_dataset = dataset.skip(train_size)
val_dataset = test_dataset.take(val_size)
test_dataset = test_dataset.skip(val_size)

In [16]:
import matplotlib.pyplot as plt
def plot_batch_sizes(ds):
  batch_sizes = [batch.shape[0] for batch in ds]
  plt.bar(range(len(batch_sizes)), batch_sizes)
  plt.xlabel('Batch number')
  plt.ylabel('Batch size')


In [44]:
# define the keras model
from keras import models
from keras import layers
from keras import regularizers
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.optimizers import Adam


In [46]:
model = Sequential()
model.add(Dense(8,input_dim = 8,activation = 'relu'))
model.add(Dropout(0.1))
model.add(Dense(4,input_dim = 8,activation = 'relu'))
model.add(Dropout(0.1))
model.add(Dense(1,activation = 'sigmoid'))

adam = Adam(lr = 0.001)


In [50]:
model.compile(loss = 'binary_crossentropy',optimizer = adam,metrics = ['accuracy'])
 # fit the keras model on the dataset
model.fit(train_dataset, epochs=150, batch_size=10)

Epoch 1/150


ValueError: ignored