<a href="https://colab.research.google.com/github/lilrachel1985/Diabetes/blob/main/tensorflowdiabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd

train_data_dir = ('https://drive.google.com/file/d/1S1u27Zy7r5rK68Bmf-7W-5GLRw4z5eHq/view?usp=drive_link')
print(train_data_dir)


https://drive.google.com/file/d/1S1u27Zy7r5rK68Bmf-7W-5GLRw4z5eHq/view?usp=drive_link


In [ ]:
my_file = tf.keras.utils.get_file("diabetes.csv", 'https://drive.google.com/file/d/1S1u27Zy7r5rK68Bmf-7W-5GLRw4z5eHq/view?usp=drive_link')

   8192/Unknown - 0s 0us/step

1. Simple Batching

In [14]:
dataset_diab1 = tf.data.Dataset.range(100)
dataset_diab2 = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((dataset_diab1, dataset_diab2))


In [15]:


dataset = tf.data.Dataset.zip((dataset_diab1, dataset_diab2))

In [16]:

batched_dataset = dataset.batch(4)

for batch in batched_dataset.take(4):
  print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3]), array([ 0, -1, -2, -3])]
[array([4, 5, 6, 7]), array([-4, -5, -6, -7])]
[array([ 8,  9, 10, 11]), array([ -8,  -9, -10, -11])]
[array([12, 13, 14, 15]), array([-12, -13, -14, -15])]


In [17]:
batched_dataset

<_BatchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.int64, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [18]:

print("dataset after applying batch method")
for batch in batched_dataset:
    print(batch)

dataset after applying batch method
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 0, -1, -2, -3])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 5, 6, 7])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-4, -5, -6, -7])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 8,  9, 10, 11])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([ -8,  -9, -10, -11])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([12, 13, 14, 15])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-12, -13, -14, -15])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([16, 17, 18, 19])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-16, -17, -18, -19])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([20, 21, 22, 23])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-20, -21, -22, -23])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([24, 25, 26, 27])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([-2

2. Batching tensors with padding

In [ ]:
record_defaults = [999, 999] # Only provide defaults for the selected columns
dataset = tf.data.experimental.CsvDataset("diabetes.csv", record_defaults, select_cols=[1, 3])
dataset = dataset.map(lambda *items: tf.stack(items))
dataset

In [20]:
record_defaults = [999,999,999,999]
dataset = tf.data.experimental.CsvDataset("missing.csv", record_defaults)
dataset = dataset.map(lambda *items: tf.stack(items))
dataset

<_MapDataset element_spec=TensorSpec(shape=(4,), dtype=tf.int32, name=None)>

In [22]:
def get_dataset_partitions_tf(dataset, dataset_size, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1

    if shuffle:
        # Specify seed to always have the same split distribution between runs
        dataset = dataset.shuffle(shuffle_size, seed=12)

    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)

    train_ds = dataset.take(train_size)
    val_ds = dataset.skip(train_size).take(val_size)
    test_ds = dataset.skip(train_size).skip(val_size)

    return train_ds, val_ds, test_ds

In [ ]:
!pip install scikit-plot